language: ruby
before_install:
  - gem install bundler
  - gem install redcarpet
rvm:
  - 2.0.0
  - 1.9.3
script: bundle exec rake
notifications:
  email:
    on_success: never
    on_failure: always